### ISSUE TITLE
Having trouble building release version

### ISSUE THREAD

**Issue by rgleason** [Rasbats/vfkaps_pi#1]
What binaries are required?
I get these errors:

Build FAILED.

"C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj" (default target) (3) ->
(Link target) ->
  vfkaps_pi.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall opencpn_plu
gin_114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) referenced in function "public:
 virtual void * __thiscall opencpn_plugin_114::`vector deleting destructor'(unsigned int)" (??_Eope
ncpn_plugin_114@@UAEPAXI@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxp
roj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall opencp
n_plugin_114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) [C:\Users\Rick\Documents\G
itHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall
opencpn_plugin_114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) [C:\Users\Rick\Docum
ents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall PlugInChart
BaseExtended::~PlugInChartBaseExtended(void)" (??1PlugInChartBaseExtended@@UAE@XZ) referenced in fu
nction "public: virtual void * __thiscall PlugInChartBaseExtended::`vector deleting destructor'(uns
igned int)" (??_EPlugInChartBaseExtended@@UAEPAXI@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkap
s_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall PlugIn
ChartBaseExtended::~PlugInChartBaseExtended(void)" (??1PlugInChartBaseExtended@@UAE@XZ) [C:\Users\R
ick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall
PlugInChartBaseExtended::~PlugInChartBaseExtended(void)" (??1PlugInChartBaseExtended@@UAE@XZ) [C:\U
sers\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::RenderRegionViewOnGL(class wxGLContext const &,class PlugIn_ViewPort const &,clas
s wxRegion const &,bool)" (?RenderRegionViewOnGL@PlugInChartBaseExtended@@UAEHABVwxGLContext@@ABVPl
ugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_p
i.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::RenderRegionViewOnGL(class wxGLContext const &,class PlugIn_ViewPort const &
,class wxRegion const &,bool)" (?RenderRegionViewOnGL@PlugInChartBaseExtended@@UAEHABVwxGLContext@@
ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfk
aps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::RenderRegionViewOnGL(class wxGLContext const &,class PlugIn_ViewPort c
onst &,class wxRegion const &,bool)" (?RenderRegionViewOnGL@PlugInChartBaseExtended@@UAEHABVwxGLCon
text@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\bui
ld\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual class wxBitmap & __thi
scall PlugInChartBaseExtended::RenderRegionViewOnDCNoText(class PlugIn_ViewPort const &,class wxReg
ion const &)" (?RenderRegionViewOnDCNoText@PlugInChartBaseExtended@@UAEAAVwxBitmap@@ABVPlugIn_ViewP
ort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual class wxBitmap &
__thiscall PlugInChartBaseExtended::RenderRegionViewOnDCNoText(class PlugIn_ViewPort const &,class
wxRegion const &)" (?RenderRegionViewOnDCNoText@PlugInChartBaseExtended@@UAEAAVwxBitmap@@ABVPlugIn_
ViewPort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxpr
oj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual class wxBit
map & __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCNoText(class PlugIn_ViewPort const &,
class wxRegion const &)" (?RenderRegionViewOnDCNoText@PlugInChartBaseExtended@@UAEAAVwxBitmap@@ABVP
lugIn_ViewPort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi
.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall PlugIn
ChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxMemoryDC &,class PlugIn_ViewPort const &,cl
ass wxRegion const &)" (?RenderRegionViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@
ABVPlugIn_ViewPort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkap
s_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall P
lugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxMemoryDC &,class PlugIn_ViewPort const
 &,class wxRegion const &)" (?RenderRegionViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemor
yDC@@ABVPlugIn_ViewPort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\
vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual bool __this
call PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxMemoryDC &,class PlugIn_ViewPort
 const &,class wxRegion const &)" (?RenderRegionViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVw
xMemoryDC@@ABVPlugIn_ViewPort@@ABVwxRegion@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\
build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::RenderRegionViewOnGLNoText(class wxGLContext const &,class PlugIn_ViewPort const
&,class wxRegion const &,bool)" (?RenderRegionViewOnGLNoText@PlugInChartBaseExtended@@UAEHABVwxGLCo
ntext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\bu
ild\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::RenderRegionViewOnGLNoText(class wxGLContext const &,class PlugIn_ViewPort c
onst &,class wxRegion const &,bool)" (?RenderRegionViewOnGLNoText@PlugInChartBaseExtended@@UAEHABVw
xGLContext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_
pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::RenderRegionViewOnGLNoText(class wxGLContext const &,class PlugIn_View
Port const &,class wxRegion const &,bool)" (?RenderRegionViewOnGLNoText@PlugInChartBaseExtended@@UA
EHABVwxGLContext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\v
fkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::RenderRegionViewOnGLTextOnly(class wxGLContext const &,class PlugIn_ViewPort cons
t &,class wxRegion const &,bool)" (?RenderRegionViewOnGLTextOnly@PlugInChartBaseExtended@@UAEHABVwx
GLContext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_p
i\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::RenderRegionViewOnGLTextOnly(class wxGLContext const &,class PlugIn_ViewPort
 const &,class wxRegion const &,bool)" (?RenderRegionViewOnGLTextOnly@PlugInChartBaseExtended@@UAEH
ABVwxGLContext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfk
aps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::RenderRegionViewOnGLTextOnly(class wxGLContext const &,class PlugIn_Vi
ewPort const &,class wxRegion const &,bool)" (?RenderRegionViewOnGLTextOnly@PlugInChartBaseExtended
@@UAEHABVwxGLContext@@ABVPlugIn_ViewPort@@ABVwxRegion@@_N@Z) [C:\Users\Rick\Documents\GitHub\o-plug
in\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual class ListOfPI_S57Obj
* __thiscall PlugInChartBaseExtended::GetObjRuleListAtLatLon(float,float,float,class PlugIn_ViewPor
t *)" (?GetObjRuleListAtLatLon@PlugInChartBaseExtended@@UAEPAVListOfPI_S57Obj@@MMMPAVPlugIn_ViewPor
t@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual class ListOfPI_S5
7Obj * __thiscall PlugInChartBaseExtended::GetObjRuleListAtLatLon(float,float,float,class PlugIn_Vi
ewPort *)" (?GetObjRuleListAtLatLon@PlugInChartBaseExtended@@UAEPAVListOfPI_S57Obj@@MMMPAVPlugIn_Vi
ewPort@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual class ListO
fPI_S57Obj * __thiscall PlugInChartBaseExtended::GetObjRuleListAtLatLon(float,float,float,class Plu
gIn_ViewPort *)" (?GetObjRuleListAtLatLon@PlugInChartBaseExtended@@UAEPAVListOfPI_S57Obj@@MMMPAVPlu
gIn_ViewPort@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual class wxString __thisc
all PlugInChartBaseExtended::CreateObjDescriptions(class ListOfPI_S57Obj *)" (?CreateObjDescription
s@PlugInChartBaseExtended@@UAE?AVwxString@@PAVListOfPI_S57Obj@@@Z) [C:\Users\Rick\Documents\GitHub\
o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual class wxString __
thiscall PlugInChartBaseExtended::CreateObjDescriptions(class ListOfPI_S57Obj *)" (?CreateObjDescri
ptions@PlugInChartBaseExtended@@UAE?AVwxString@@PAVListOfPI_S57Obj@@@Z) [C:\Users\Rick\Documents\Gi
tHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual class wxStr
ing __thiscall PlugInChartBaseExtended::CreateObjDescriptions(class ListOfPI_S57Obj *)" (?CreateObj
Descriptions@PlugInChartBaseExtended@@UAE?AVwxString@@PAVListOfPI_S57Obj@@@Z) [C:\Users\Rick\Docume
nts\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::GetNoCOVREntries(void)" (?GetNoCOVREntries@PlugInChartBaseExtended@@UAEHXZ) [C:\U
sers\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::GetNoCOVREntries(void)" (?GetNoCOVREntries@PlugInChartBaseExtended@@UAEHXZ)
[C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::GetNoCOVREntries(void)" (?GetNoCOVREntries@PlugInChartBaseExtended@@UA
EHXZ) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::GetNoCOVRTablePoints(int)" (?GetNoCOVRTablePoints@PlugInChartBaseExtended@@UAEHH@
Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::GetNoCOVRTablePoints(int)" (?GetNoCOVRTablePoints@PlugInChartBaseExtended@@U
AEHH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::GetNoCOVRTablePoints(int)" (?GetNoCOVRTablePoints@PlugInChartBaseExten
ded@@UAEHH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall PlugInC
hartBaseExtended::GetNoCOVRTablenPoints(int)" (?GetNoCOVRTablenPoints@PlugInChartBaseExtended@@UAEH
H@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall Pl
ugInChartBaseExtended::GetNoCOVRTablenPoints(int)" (?GetNoCOVRTablenPoints@PlugInChartBaseExtended@
@UAEHH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual int __thisc
all PlugInChartBaseExtended::GetNoCOVRTablenPoints(int)" (?GetNoCOVRTablenPoints@PlugInChartBaseExt
ended@@UAEHH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual float * __thiscall Plu
gInChartBaseExtended::GetNoCOVRTableHead(int)" (?GetNoCOVRTableHead@PlugInChartBaseExtended@@UAEPAM
H@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual float * __thiscal
l PlugInChartBaseExtended::GetNoCOVRTableHead(int)" (?GetNoCOVRTableHead@PlugInChartBaseExtended@@U
AEPAMH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual float * __t
hiscall PlugInChartBaseExtended::GetNoCOVRTableHead(int)" (?GetNoCOVRTableHead@PlugInChartBaseExten
ded@@UAEPAMH@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkaps_pi.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall PlugIn
ChartBaseExtended::ClearPLIBTextList(void)" (?ClearPLIBTextList@PlugInChartBaseExtended@@UAEXXZ) [C
:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsgui_impl.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall P
lugInChartBaseExtended::ClearPLIBTextList(void)" (?ClearPLIBTextList@PlugInChartBaseExtended@@UAEXX
Z) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  vfkapsOverlayFactory.obj : error LNK2001: unresolved external symbol "public: virtual void __this
call PlugInChartBaseExtended::ClearPLIBTextList(void)" (?ClearPLIBTextList@PlugInChartBaseExtended@
@UAEXXZ) [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\Release\vfkaps_pi.dll : fatal error LNK11
20: 14 unresolved externals [C:\Users\Rick\Documents\GitHub\o-plugin\vfkaps_pi\build\vfkaps_pi.vcxp
roj]

    0 Warning(s)
    43 Error(s)

**Comment by Rasbats** [comment]
Building standalone the file 'ocpn_plugin.h' needs to match the 'opencpn.lib' file you add to the build folder.
I used '.h' from a 4.8.0 build of opencpn. You need to match this with the '.lib' from 4.8.0. I will add that lib to the v0.6 release for download if needed.

**Comment by rgleason** [comment]
Thanks.. Builds now.


Build succeeded.

"C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\build\ALL_BUILD.vcxproj" (default target) (1)
 ->
"C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\build\vfkaps_pi.vcxproj" (default target) (3)
 ->
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\src\vfkapsgui_impl.cpp(1098): warning C4018:
 '<' : signed/unsigned mismatch [C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\build\vfkaps_
pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\src\vfkapsgui_impl.cpp(1109): warning C4018:
 '<' : signed/unsigned mismatch [C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\build\vfkaps_
pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\src\vfkapsgui_impl.cpp(1134): warning C4018:
 '<' : signed/unsigned mismatch [C:\Users\Rick\Documents\GitHub\o-plugin\mr-vfkaps_pi\build\vfkaps_
pi.vcxproj]

    3 Warning(s)
    0 Error(s)
