### ISSUE TITLE
Null pointer deref

### ISSUE THREAD

**Issue by transmitterdan** [Rasbats/vfkaps_pi#4]
Mike,

When I select anchorage tab and then select United States I get a null pointer deref in function wxJSONValue::COW(). It assumes that GetRefData() will always return a non-null pointer but it seems that it can. Perhaps this is an error in the anchorage data but not really sure. The root function that starts the problem is void Dlg::ReadJsonCountryMarkers(wxString injson) but I am unsure why it fails. The country code is "222" but perhaps something in the data file that was downloaded causes the problem.

**Comment by Rasbats** [comment]
The error checking in the code is minimal/non-existent. A suggestion for detecting the non-null pointer would be appreciated. (How did you detect this error? Nothing is showing in my debug version and the plugin works without error at this end)
