### ISSUE TITLE
Changes for OSX

### ISSUE THREAD

**Issue by ptulp** [Rasbats/vfkaps_pi#5]
Mike,

To build for OSX two changes are needed.

1: Change file buildosx/InstallOSX/DR_pi.pkgproj.in to buildosx/InstallOSX/vfkaps_pi.pkgproj.in

2: To use the standard pkgproj file it needs a data directory in vfkaps_pi. This directory can be empty.

I build the OSX version in ptulp/vfkaps_pi Prerelease v1.1.1

Regards,
Peter

**Comment by Rasbats** [comment]
Thanks Peter. Yes I will correct that file. I used DR_pi as a template.

Should I add the OSX version to my VFKaps release? Kathi could highlight that version on OpenCPN.org, which only points to the Windows release at the moment.

Mike

**Comment by ptulp** [comment]
Yes, you could add my build to the releases although I didn't test the plugin extensively.
But as it is build against your code I don't expect much problems.

Peter

**Comment by rgleason** [comment]
Mike, do you know how to do osx PI?
CarstenWL is asking about a Weatherfax version for Mac OSX. 
and while we are talking about that there is climatology, weather_routing, celestial_navigation, weatherfax, statusbar, projections, sweep_plot, and what have I missed of Sean's?

I also notice someone asking about Tactics for Mac who was trying to compile it....

**Comment by Rasbats** [comment]
Peter ... I am not running OSX. Could you help Rick with compiling some of those other plugins. 

Thanks for the use of the .img for my GitHub.

Mike

**Comment by rgleason** [comment]
Sorry, I totally misunderstood. Peter has been great about compiling for Mac, and it would probably be a good time to compile Sean's plugins for MAC, how do we get them as a release on the downloads page?

Could Peter use the "release" feature for his Mac versions? Then Kathi could make a link to each of his fork's release URL?

Peter, Sean's repository's for weather_routing, weatherfax, celestial_nav and most of his other plugins are current as far as I know.  (We were ahead of him for awhile.)

Thanks.
